### ISSUE TITLE
Question: How to build this repo

### ISSUE THREAD

**Issue by jostyee** [RyanKung/shadowsocks4blackberry#1]
Hi,
I have a BlackBerry Passport but have no idea of BB10 dev environment, can you please offer detailed steps of this repo, or better release a binary, thanks in advance.

**Comment by RyanKung** [comment]
To build the repo, just run `build4blackberry.sh` under the `QNX ENV`:

http://devblog.blackberry.com/2013/05/building-apps-without-an-ide/

And the released files:

https://github.com/RyanKung/shadowsocks4blackberry/releases/tag/0.1

**Comment by jostyee** [comment]
Thank you for your help, I'll test the files later.
